import { Project, Experience, Skill, Certificate, NavigationItem } from '../types';

export const NAVIGATION_ITEMS: NavigationItem[] = [
  { id: 'home', label: 'Home', href: '#home' },
  { id: 'about', label: 'About', href: '#about' },
  { id: 'skills', label: 'Skills', href: '#skills' },
  { id: 'experience', label: 'Experience', href: '#experience' },
  { id: 'certificates', label: 'Certificates', href: '#certificates' },
  { id: 'projects', label: 'Projects', href: '#projects' },
  { id: 'contact', label: 'Contact', href: '#contact' },
];

export const SKILLS: Skill[] = [
  // Creative Software
  { name: 'Adobe Illustrator', percentage: 98, category: 'creative' },
  { name: 'Adobe Photoshop', percentage: 95, category: 'creative' },
  { name: 'Canva', percentage: 95, category: 'creative' },
  { name: 'Adobe InDesign', percentage: 92, category: 'creative' },
  { name: 'Adobe XD', percentage: 90, category: 'creative' },
  { name: 'CapCut', percentage: 90, category: 'creative' },
  // Office/Productivity
  { name: 'Microsoft Word', percentage: 85, category: 'productivity' },
  { name: 'Microsoft Excel', percentage: 80, category: 'productivity' },
];

export const EXPERIENCE: Experience[] = [
  {
    id: 1,
    type: 'professional',
    title: 'Freelance Graphic Designer',
    period: '2026 - Present',
    description: 'Independent design professional specializing in brand identity and social media content creation.',
    achievements: [
      'Social Media Design: Custom graphics and carousels yielding 40% engagement increases',
      'Brand Identity: Complete visual identity systems and guidelines',
      'Marketing Graphics: Campaign-specific design assets',
      'Campaign Design: Integrated multi-platform campaigns',
      'Visual Reels: Motion graphics and video content creation',
    ],
  },
  {
    id: 2,
    type: 'professional',
    title: 'Junior Graphic Designer',
    period: '2024 - 2026',
    description: 'Collaborative design role focusing on brand system development and production.',
    achievements: [
      'Client Brandboards: Comprehensive brand guideline documentation',
      'Typographic Systems: Advanced font hierarchy and styling',
      'Daily Feed Posts: High-volume social media asset production',
      'Vector Logos: Professional logo exports and optimization',
      'Print Setup: Print-ready file preparation and specifications',
    ],
  },
  {
    id: 3,
    type: 'education',
    institution: 'CIS College',
    title: 'BT3 Certificate in Graphic Design',
    period: '2025/2026',
    description: 'Advanced studies in design principles and professional practice.',
    achievements: [
      'Advanced Typographic Structure',
      'Packaging Layout & Design',
      'Professional Printmaking',
      'Color Theory & Application',
      'Digital Asset Management',
    ],
  },
  {
    id: 4,
    type: 'education',
    institution: 'CIS College',
    title: 'BT2 Certificate in Graphic Design',
    period: '2024/2025',
    description: 'Intermediate design certification focusing on core competencies.',
  },
  {
    id: 5,
    type: 'education',
    institution: 'CIS College',
    title: 'BT1 Certificate in Graphic Design',
    period: '2023/2024',
    description: 'Foundation certificate establishing core design principles and techniques.',
  },
];

export const CERTIFICATES: Certificate[] = [
  {
    id: 1,
    title: 'BT3 Certificate in Graphic Design',
    issuer: 'CIS College',
    year: '2025/2026',
    description: 'Advanced diploma in graphic design and brand systems.',
  },
  {
    id: 2,
    title: 'BT2 Certificate in Graphic Design',
    issuer: 'CIS College',
    year: '2024/2025',
  },
  {
    id: 3,
    title: 'BT1 Certificate in Graphic Design',
    issuer: 'CIS College',
    year: '2023/2024',
  },
  {
    id: 4,
    title: 'Adobe Illustrator Master Course',
    issuer: 'BasementX',
    year: '2024',
  },
  {
    id: 5,
    title: 'Adobe Photoshop Professional Course',
    issuer: 'BasementX',
    year: '2024',
  },
  {
    id: 6,
    title: 'Adobe InDesign Layout Course',
    issuer: 'BasementX',
    year: '2024',
  },
  {
    id: 7,
    title: 'Creative Graphic Design & Composition Studies',
    issuer: 'YouTube Platforms',
    year: 'Ongoing',
  },
];

export const PROJECTS: Project[] = [
  {
    id: 1,
    title: 'Brand Reveal Poster',
    category: 'Social Media Poster',
    year: 2025,
    tools: ['Adobe Illustrator', 'Adobe Photoshop'],
    description: 'Elegant brand reveal campaign poster with modern typography and luxury aesthetics.',
    objectives: ['Brand awareness', 'Social media engagement', 'Visual hierarchy'],
    image: '/projects/brand-reveal.jpg',
  },
  {
    id: 2,
    title: 'Social Media Campaign',
    category: 'Social Media Poster',
    year: 2025,
    tools: ['Canva', 'Adobe Photoshop'],
    description: 'Cohesive multi-post social media campaign with consistent branding.',
    objectives: ['Campaign coherence', 'Audience engagement', 'Brand consistency'],
    image: '/projects/social-campaign.jpg',
  },
  {
    id: 3,
    title: 'Editorial Fashion Poster',
    category: 'Social Media Poster',
    year: 2025,
    tools: ['Adobe Illustrator', 'Adobe InDesign'],
    description: 'High-fashion editorial layout with sophisticated typography.',
    objectives: ['Fashion marketing', 'Editorial design', 'Visual storytelling'],
    image: '/projects/fashion-poster.jpg',
  },
  {
    id: 4,
    title: 'Vanguard Coffee Poster',
    category: 'Social Media Poster',
    year: 2025,
    tools: ['Adobe Illustrator', 'Adobe Photoshop'],
    description: 'Premium coffee brand marketing poster with minimalist design approach.',
    objectives: ['Brand positioning', 'Product showcase', 'Luxury aesthetics'],
    image: '/projects/vanguard-coffee.jpg',
  },
  {
    id: 5,
    title: 'Aura Cosmetics Poster',
    category: 'Social Media Poster',
    year: 2025,
    tools: ['Canva', 'Adobe Photoshop'],
    description: 'Cosmetics brand campaign with elegant visual hierarchy.',
    objectives: ['Product launch', 'Audience targeting', 'Brand awareness'],
    image: '/projects/aura-cosmetics.jpg',
  },
  {
    id: 6,
    title: 'Exhibition Promotional Poster',
    category: 'Social Media Poster',
    year: 2025,
    tools: ['Adobe Illustrator', 'Adobe InDesign'],
    description: 'Event promotion poster with contemporary design elements.',
    objectives: ['Event promotion', 'Attendance generation', 'Visual appeal'],
    image: '/projects/exhibition-poster.jpg',
  },
  {
    id: 7,
    title: 'Sonder Studio Logo',
    category: 'Logo Design',
    year: 2025,
    tools: ['Adobe Illustrator'],
    description: 'Modern studio branding with geometric and organic elements.',
    objectives: ['Brand identity', 'Logo mark recognition', 'Versatility'],
    image: '/projects/sonder-logo.jpg',
  },
  {
    id: 8,
    title: 'Chronos Watch Logo',
    category: 'Logo Design',
    year: 2025,
    tools: ['Adobe Illustrator'],
    description: 'Luxury watch brand identity with precision-engineered aesthetics.',
    objectives: ['Luxury branding', 'Time symbolism', 'Premium positioning'],
    image: '/projects/chronos-logo.jpg',
  },
  {
    id: 9,
    title: 'Prestige Whiskey Poster',
    category: 'Social Media Poster',
    year: 2025,
    tools: ['Adobe Photoshop', 'Adobe Illustrator'],
    description: 'Premium spirit brand marketing with sophisticated composition.',
    objectives: ['Luxury marketing', 'Brand prestige', 'Target audience appeal'],
    image: '/projects/whiskey-poster.jpg',
  },
  {
    id: 10,
    title: 'Bespoke Product Poster',
    category: 'Social Media Poster',
    year: 2025,
    tools: ['Canva', 'Adobe Photoshop'],
    description: 'Custom product showcase with artisanal design approach.',
    objectives: ['Product presentation', 'Handcrafted narrative', 'Premium positioning'],
    image: '/projects/bespoke-product.jpg',
  },
  {
    id: 11,
    title: 'Corporate Marketing Poster',
    category: 'Social Media Poster',
    year: 2025,
    tools: ['Adobe InDesign', 'Adobe Photoshop'],
    description: 'Enterprise brand communication with professional aesthetics.',
    objectives: ['Corporate messaging', 'Brand authority', 'Professional image'],
    image: '/projects/corporate-marketing.jpg',
  },
  {
    id: 12,
    title: 'Digital Advertisement Poster',
    category: 'Social Media Poster',
    year: 2025,
    tools: ['Adobe Illustrator', 'Canva'],
    description: 'Multi-platform digital advertising creative with responsive design.',
    objectives: ['Digital reach', 'Conversion optimization', 'Platform adaptation'],
    image: '/projects/digital-ad.jpg',
  },
  {
    id: 13,
    title: 'Eco-Friendly Box Poster',
    category: 'Social Media Poster',
    year: 2025,
    tools: ['Adobe Illustrator', 'Adobe InDesign'],
    description: 'Sustainable brand packaging and promotional design.',
    objectives: ['Environmental messaging', 'Brand values', 'Packaging presentation'],
    image: '/projects/eco-box.jpg',
  },
];

export const CONTACT_INFO = {
  email: 'zreikali222@gmail.com',
  phone: '+961 81 257 231',
  location: 'Beirut, Lebanon',
  coordinates: { lat: 33.8938, lng: 35.5018 },
  status: 'AVAILABLE FOR PROJECTS',
  bookingStatus: 'CURRENTLY BOOKING FOR MID-2026 COHORTS',
};

export const SOCIAL_LINKS = {
  instagram: '#',
  linkedin: '#',
  behance: '#',
};
